### ISSUE TITLE
compiling on Linux OK after simple source edit

### ISSUE THREAD

**Issue by tissatussa** [rafid-dev/jet#17]
while compiling your v1.1 source on Linux, i encounter this error in the files `/src/nnue.cpp` and `/src/nnue/accumulator.hpp` :

`error: no member named 'memcpy' in namespace 'std'`

the function `memcpy` is defined in header `<cstring>`, so i had to add `#include <cstring>` on top of those files.
this way i was able to compile Jet v1.1 and it runs fine in CuteChess !

Note: besides that, i had (only) 1 warning in `src/nnue.cpp` :
```
variable 'bytesRead' set but not used [-Wunused-but-set-variable]
uint64_t bytesRead = 0;
```

[ i'm on Xubuntu 22.04 ]

**Comment by rafid-dev** [comment]
sorry for late response, I wasn't on. So <cstring> header was included in dev version while in the 1.1 it wasn't there. I'm glad that you could figure it out.
