### ISSUE TITLE
display eval zeros

### ISSUE THREAD

**Issue by tissatussa** [rafid-dev/jet#22]
your engine runs fine in CuteChess (GUI) but the move list doesn't show the eval values next to each (best)move : all eval values are "0.00" .. however, in the evaluation pane the eval values ARE shown at each depth ..

i guess you never mentioned and this can be solved easily.
btw. i tried v1.1 and v1.2, both have the same issue.

![jet-eval-zeros](https://github.com/rafid-dev/jet/assets/1109281/07366f45-2f91-4698-8f67-492b7d080dbd)

**Comment by rafid-dev** [comment]
It has been fixed in https://github.com/rafid-dev/jet/pull/23

Thanks for your patience.
